version: '3.5'
services:  
  database:
    image: "postgres:12.2"
    env_file:
      - variables.env
    environment:
      - POSTGRES_MULTIPLE_DATABASES=UltraCars,UltraCarsE2ETest
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ultra-net

  redis:
    image: "redis:alpine"
    command: redis-server
    networks:
      - ultra-net

  webapp:
    container_name: ultra_cars_test
    build: .
    ports:
      - 3001:3000
    command: sh -c './wait-for.sh database:5432 -- yarn start'
    env_file:
      - variables.env
    depends_on:
      - database
      - redis
    networks:
      - ultra-net
networks:
  ultra-net:
    external: true

volumes:
  db-data:
    driver: local